# Generated by Django 2.2.13 on 2020-06-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200621_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descritption',
            new_name='description',
        ),
    ]
